// <auto-generated />
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260414120000_AdicionarIndexesPerformance")]
    partial class AdicionarIndexesPerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Index-only migration via raw SQL — sem alteração de schema no modelo EF.
            // BuildTargetModel deixado vazio intencionalmente;
            // modelo idêntico à migration anterior.
            // Para regenerar corretamente: dotnet ef migrations add --no-build na raiz do Infra.Postgre.
        }
    }
}
