// <auto-generated />
using System;
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260417165852_AddIndexValidadeEm")]
    partial class AddIndexValidadeEm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyStock.Domain.Entities.AnuncioIa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstrucoesUsadas")
                        .HasColumnType("text");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProdutoVariacaoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Salvo")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TokensConsumidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("EmpresaId", "CriadoEm");

                    b.HasIndex("EmpresaId", "ProdutoId");

                    b.ToTable("anuncios_ia", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.AssinaturaEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PlanoId");

                    b.ToTable("assinaturas_empresa", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Acao");

                    b.HasIndex("DataHora");

                    b.HasIndex("UsuarioId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ConfiguracaoLoja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiasAlertaParado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<int>("DiasAlertaValidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<bool>("FifoAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LojaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("BRL");

                    b.Property<bool>("NotificarEstoqueCritico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarParado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarReposicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("NotificarValidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("QuantidadeMinimaPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("America/Sao_Paulo");

                    b.HasKey("Id");

                    b.HasIndex("LojaId")
                        .IsUnique();

                    b.ToTable("configuracoes_loja", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Contato")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FretePadrao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("LeadTimeEstimadoDias")
                        .HasColumnType("integer");

                    b.Property<decimal?>("LeadTimeRealMedioDias")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PedidoMinimo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ativo");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ItemEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChavePesquisa")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CodigoLote")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CodigoMarketplace")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescricaoAnuncio")
                        .HasColumnType("text");

                    b.Property<int>("DiasSemMovimentacao")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EntradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("FornecedorNome")
                        .HasColumnType("text");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecoVendaSugerido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrevisaoZeramentoDias")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProdutoVariacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeInicial")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeMinima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("UltimaMovimentacaoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidadeEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VariacaoDescricao")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<decimal>("VelocidadeSaidaDiaria")
                        .HasColumnType("decimal(10,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("LojaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVariacaoId");

                    b.HasIndex("EmpresaId", "QuantidadeAtual")
                        .HasDatabaseName("ix_itens_estoque_empresa_quantidade");

                    b.HasIndex("EmpresaId", "UltimaMovimentacaoEm")
                        .HasDatabaseName("ix_itens_estoque_empresa_ultima_mov");

                    b.HasIndex("EmpresaId", "ValidadeEm")
                        .HasDatabaseName("ix_itens_estoque_empresa_validade");

                    b.ToTable("itens_estoque", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("ItemEstoqueId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProdutoVariacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("VariacaoSnapshot")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemEstoqueId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVariacaoId");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_itens_venda_venda_id");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Loja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ativa");

                    b.ToTable("lojas", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoReferencia")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EstornadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemEstoqueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MovimentacaoEstornadaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProdutoVariacaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemEstoqueId");

                    b.HasIndex("MovimentacaoEstornadaId")
                        .HasFilter("\"MovimentacaoEstornadaId\" IS NOT NULL");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVariacaoId");

                    b.HasIndex("VendaId");

                    b.HasIndex("EmpresaId", "Natureza")
                        .HasDatabaseName("ix_movimentacoes_empresa_natureza");

                    b.HasIndex("EmpresaId", "Tipo", "DataMovimentacao")
                        .HasDatabaseName("ix_movimentacoes_empresa_tipo_data");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severidade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Media");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Lida", "CriadaEm");

                    b.HasIndex("EmpresaId", "Severidade", "Lida");

                    b.HasIndex("EmpresaId", "TipoAlerta", "ReferenciaId");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.PedidoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Canal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PrevisaoEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Tracking")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("EmpresaId", "DataPedido");

                    b.HasIndex("EmpresaId", "FornecedorId", "Status");

                    b.ToTable("pedidos_fornecedor", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("perfis_permissoes", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("LimiteGeracoesIaMensais")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteLojas")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteProdutos")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("planos", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AlteradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("AtributosJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ControlaValidade")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CustoReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescricaoBase")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FotosJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Marca")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal?>("MargemEstimada")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("ObservacaoInterna")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("PrecoReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SkuBase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SugestaoDescricaoAnuncio")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SubcategoriaId");

                    b.HasIndex("EmpresaId", "AlteradoEm")
                        .HasDatabaseName("ix_produtos_empresa_alteradoem");

                    b.HasIndex("EmpresaId", "SkuBase")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_empresa_sku_unique")
                        .HasFilter("\"SkuBase\" IS NOT NULL");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("ix_produtos_empresa_status");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoAlteracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AlteracoesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EmpresaId", "ProdutoId");

                    b.HasIndex("ProdutoId", "AlteradoEm");

                    b.ToTable("produto_alteracoes", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuantidadeReferencia")
                        .HasColumnType("integer");

                    b.Property<Guid?>("VariacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("VariacaoPadrao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VariacaoId");

                    b.ToTable("produto_caracteristicas", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoEmbalagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Padrao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("produto_embalagens", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoVariacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("AtributosJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoComercial")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProdutoId", "Sku");

                    b.ToTable("produto_variacoes", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpCriacao")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEm");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpCriacao")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEm");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reset_tokens", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.UsoIa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGeracoes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("uso_ia", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TemaPreferido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("light");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId", "EmpresaId");

                    b.ToTable("usuarios_empresas", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AtribuidoPorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_perfis", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LojaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroNotaFiscal")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LojaId");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.AnuncioIa", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.AssinaturaEmpresa", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Categoria", "CategoriaPai")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPaiId");

                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Categorias")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPai");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ConfiguracaoLoja", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Fornecedor", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ItemEstoque", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EasyStock.Domain.Entities.Loja", "Loja")
                        .WithMany("Itens")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany("ItensEstoque")
                        .HasForeignKey("ProdutoVariacaoId");

                    b.OwnsOne("EasyStock.Domain.ValueObjects.Dimensoes", "DimensoesReais", b1 =>
                        {
                            b1.Property<Guid>("ItemEstoqueId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Altura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("altura_real");

                            b1.Property<decimal>("Comprimento")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("comprimento_real");

                            b1.Property<decimal>("Largura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("largura_real");

                            b1.Property<decimal>("Peso")
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("peso_real");

                            b1.HasKey("ItemEstoqueId");

                            b1.ToTable("itens_estoque");

                            b1.WithOwner()
                                .HasForeignKey("ItemEstoqueId");
                        });

                    b.Navigation("DimensoesReais");

                    b.Navigation("Empresa");

                    b.Navigation("Fornecedor");

                    b.Navigation("Loja");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoVariacao");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.ItemEstoque", "ItemEstoque")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ItemEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoVariacaoId");

                    b.HasOne("EasyStock.Domain.Entities.Venda", "Venda")
                        .WithMany("ItensVenda")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemEstoque");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoVariacao");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Loja", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Lojas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.ItemEstoque", "ItemEstoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ItemEstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.MovimentacaoEstoque", "MovimentacaoEstornada")
                        .WithMany()
                        .HasForeignKey("MovimentacaoEstornadaId");

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoVariacaoId");

                    b.HasOne("EasyStock.Domain.Entities.Venda", "Venda")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("VendaId");

                    b.Navigation("Empresa");

                    b.Navigation("ItemEstoque");

                    b.Navigation("MovimentacaoEstornada");

                    b.Navigation("Produto");

                    b.Navigation("ProdutoVariacao");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.PedidoFornecedor", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Permissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Produto", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Produtos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Categoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId");

                    b.OwnsOne("EasyStock.Domain.ValueObjects.Dimensoes", "Dimensoes", b1 =>
                        {
                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Altura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("altura");

                            b1.Property<decimal>("Comprimento")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("comprimento");

                            b1.Property<decimal>("Largura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("largura");

                            b1.Property<decimal>("Peso")
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("peso");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Categoria");

                    b.Navigation("Dimensoes");

                    b.Navigation("Empresa");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoAlteracao", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoCaracteristica", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("CaracteristicasProduto")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.ProdutoVariacao", "Variacao")
                        .WithMany()
                        .HasForeignKey("VariacaoId");

                    b.Navigation("Empresa");

                    b.Navigation("Produto");

                    b.Navigation("Variacao");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoEmbalagem", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("EmbalagensProduto")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Embalagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EasyStock.Domain.ValueObjects.Dimensoes", "Dimensoes", b1 =>
                        {
                            b1.Property<Guid>("ProdutoEmbalagemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Altura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("altura");

                            b1.Property<decimal>("Comprimento")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("comprimento");

                            b1.Property<decimal>("Largura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("largura");

                            b1.Property<decimal>("Peso")
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("peso");

                            b1.HasKey("ProdutoEmbalagemId");

                            b1.ToTable("produto_embalagens");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoEmbalagemId");
                        });

                    b.Navigation("Dimensoes");

                    b.Navigation("Empresa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoVariacao", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("VariacoesProduto")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EasyStock.Domain.ValueObjects.Dimensoes", "DimensoesPadrao", b1 =>
                        {
                            b1.Property<Guid>("ProdutoVariacaoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Altura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("altura");

                            b1.Property<decimal>("Comprimento")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("comprimento");

                            b1.Property<decimal>("Largura")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("largura");

                            b1.Property<decimal>("Peso")
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("peso");

                            b1.HasKey("ProdutoVariacaoId");

                            b1.ToTable("produto_variacoes");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoVariacaoId");
                        });

                    b.Navigation("DimensoesPadrao");

                    b.Navigation("Empresa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ResetToken", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Empresas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Venda", b =>
                {
                    b.HasOne("EasyStock.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vendas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyStock.Domain.Entities.Loja", "Loja")
                        .WithMany("Vendas")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("CaracteristicasProduto");

                    b.Navigation("Categorias");

                    b.Navigation("EmbalagensProduto");

                    b.Navigation("ItensEstoque");

                    b.Navigation("Lojas");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Produtos");

                    b.Navigation("VariacoesProduto");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ItemEstoque", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Loja", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Permissoes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("Embalagens");

                    b.Navigation("ItensEstoque");

                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.ProdutoVariacao", b =>
                {
                    b.Navigation("ItensEstoque");

                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Perfis");
                });

            modelBuilder.Entity("EasyStock.Domain.Entities.Venda", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
