// <auto-generated />
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260514120001_EtiquetaTemplatesRedesign")]
    partial class EtiquetaTemplatesRedesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Data-only migration — sem alteração de schema.
            // BuildTargetModel deixado vazio intencionalmente;
            // modelo idêntico à migration anterior EtiquetaTemplates.
        }
    }
}
