// <auto-generated />
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260514120000_AddNfceTaxFields")]
    partial class AddNfceTaxFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
