// <auto-generated />
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260502120000_AddPedidoFornecedorItemTable")]
    partial class AddPedidoFornecedorItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Designer gerado retroativamente — BuildTargetModel não reconstruído.
            // Migration de criação da tabela pedidos_fornecedor_itens (já aplicada ao banco).
            // Para regenerar corretamente: dotnet ef migrations add --no-build na raiz do Infra.Postgre.
        }
    }
}
