// <auto-generated />
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260511120000_AddRowLevelSecurity")]
    partial class AddRowLevelSecurity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
