// <auto-generated />
using System;
using EasyStock.Infra.Postgre.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyStock.Infra.Postgre.Migrations
{
    [DbContext(typeof(EasyStockDbContext))]
    [Migration("20260513000002_AddVendaReportingColumns")]
    partial class AddVendaReportingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is maintained in EasyStockDbContextModelSnapshot.cs
        }
    }
}
