using EasyStock.Application.UseCases.AlterarSenha;
using EasyStock.Application.UseCases.AtualizarUsuarioAtual;
using EasyStock.Application.UseCases.CadastrarUsuario;
using EasyStock.Application.UseCases.EsqueciSenha;
using EasyStock.Application.UseCases.EstornarSaida;
using EasyStock.Application.UseCases.Logout;
using EasyStock.Application.UseCases.ObterUsuarioAtual;
using EasyStock.Application.UseCases.RefreshToken;
using EasyStock.Application.UseCases.ResetarSenha;
using EasyStock.Application.UseCases.AlterarSenhaUsuario;
using EasyStock.Application.UseCases.AtribuirPerfilUsuario;
using EasyStock.Application.UseCases.AtualizarFornecedor;
using EasyStock.Application.UseCases.AtualizarLoja;
using EasyStock.Application.UseCases.AtualizarUsuario;
using EasyStock.Application.UseCases.AutenticarUsuario;
using EasyStock.Application.UseCases.BuscarEstoqueInteligente;
using EasyStock.Application.UseCases.CadastrarProduto;
using EasyStock.Application.UseCases.CriarFornecedor;
using EasyStock.Application.UseCases.CriarLoja;
using EasyStock.Application.UseCases.CriarUsuario;
using EasyStock.Application.UseCases.DesativarFornecedor;
using EasyStock.Application.UseCases.DesativarLoja;
using EasyStock.Application.UseCases.DesativarUsuario;
using EasyStock.Application.UseCases.ConfiguracoesLoja;
using EasyStock.Application.UseCases.GerenciarCategoria;
using EasyStock.Application.UseCases.GerenciarProduto;
using EasyStock.Application.UseCases.GerenciarUploads;
using EasyStock.Application.UseCases.GerenciarVariacaoProduto;
using EasyStock.Application.UseCases.GerarSugestaoDescricaoAnuncio;
using EasyStock.Application.UseCases.AnuncioIa;
using EasyStock.Application.UseCases.Fornecedor;
using EasyStock.Application.UseCases.ListarFornecedores;
using EasyStock.Application.UseCases.ListarLojas;
using EasyStock.Application.UseCases.ListarPlanos;
using EasyStock.Application.UseCases.ListarUsuarios;
using EasyStock.Application.UseCases.RegistrarEmpresa;
using EasyStock.Application.UseCases.RegistrarEntradaEstoque;
using EasyStock.Application.UseCases.RegistrarSaidaEstoque;
using EasyStock.Application.UseCases.Pedido;
using EasyStock.Application.UseCases.ReativarFornecedor;
using EasyStock.Application.UseCases.ReativarLoja;
using EasyStock.Application.UseCases.ReporEstoque;
using Microsoft.Extensions.DependencyInjection;

namespace EasyStock.Application.DependencyInjection;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddEasyStockApplication(this IServiceCollection services)
    {
        services.AddScoped<AutenticarUsuarioUseCase>();
        services.AddScoped<CadastrarUsuarioUseCase>();
        services.AddScoped<RefreshTokenUseCase>();
        services.AddScoped<LogoutUseCase>();
        services.AddScoped<EsqueciSenhaUseCase>();
        services.AddScoped<ResetarSenhaUseCase>();
        services.AddScoped<ObterUsuarioAtualUseCase>();
        services.AddScoped<AtualizarUsuarioAtualUseCase>();
        services.AddScoped<AlterarSenhaUseCase>();
        services.AddScoped<RegistrarEmpresaUseCase>();
        services.AddScoped<CriarUsuarioUseCase>();
        services.AddScoped<AtualizarUsuarioUseCase>();
        services.AddScoped<AlterarSenhaUsuarioUseCase>();
        services.AddScoped<DesativarUsuarioUseCase>();
        services.AddScoped<ListarUsuariosUseCase>();
        services.AddScoped<AtribuirPerfilUsuarioUseCase>();
        services.AddScoped<CriarLojaUseCase>();
        services.AddScoped<AtualizarLojaUseCase>();
        services.AddScoped<DesativarLojaUseCase>();
        services.AddScoped<ReativarLojaUseCase>();
        services.AddScoped<ListarLojasUseCase>();
        services.AddScoped<CriarFornecedorUseCase>();
        services.AddScoped<AtualizarFornecedorUseCase>();
        services.AddScoped<DesativarFornecedorUseCase>();
        services.AddScoped<ReativarFornecedorUseCase>();
        services.AddScoped<ListarFornecedoresUseCase>();
        services.AddScoped<ObterFornecedorDetalheUseCase>();
        services.AddScoped<ObterHistoricoFornecedorUseCase>();
        services.AddScoped<ObterEstatisticasFornecedorUseCase>();
        services.AddScoped<ListarPedidosAbertosUseCase>();
        services.AddScoped<CriarPedidoFornecedorUseCase>();
        services.AddScoped<ReceberPedidoFornecedorUseCase>();
        services.AddScoped<CancelarPedidoFornecedorUseCase>();
        services.AddScoped<ObterConfiguracaoLojaUseCase>();
        services.AddScoped<AtualizarConfiguracaoLojaUseCase>();
        services.AddScoped<ResetarConfiguracaoLojaUseCase>();
        services.AddScoped<CadastrarProdutoUseCase>();
        services.AddScoped<GerenciarProdutoUseCase>();
        services.AddScoped<GerenciarVariacaoProdutoUseCase>();
        services.AddScoped<GerenciarUploadsUseCase>();
        services.AddScoped<RegistrarEntradaEstoqueUseCase>();
        services.AddScoped<RegistrarSaidaEstoqueUseCase>();
        services.AddScoped<EstornarSaidaUseCase>();
        services.AddScoped<ReporEstoqueUseCase>();
        services.AddScoped<BuscarEstoqueInteligenteUseCase>();
        services.AddScoped<GerarSugestaoDescricaoAnuncioUseCase>();
        services.AddScoped<GerarAnuncioStreamingUseCase>();
        services.AddScoped<SalvarRascunhoAnuncioUseCase>();
        services.AddScoped<ListarAnunciosUseCase>();
        services.AddScoped<ExcluirAnuncioUseCase>();
        services.AddScoped<ObterUsoIaUseCase>();
        services.AddScoped<GerenciarCategoriaUseCase>();
        services.AddScoped<ListarPlanosUseCase>();

        return services;
    }
}
